### ISSUE TITLE
How to make windows stack one of top of another, like in the screenshot?

### ISSUE THREAD

**Issue by adilno54** [peterfajdiga/karousel#1]
![d](https://github.com/peterfajdiga/karousel/assets/137398446/3c3d87d4-83e7-4599-a9a2-be975185dc33)
I tested all shortcuts, no one give me the stacking feature, nor I can with the mouse.

**Comment by peterfajdiga** [comment]
It's Ctrl+Shift+A (move window to the left).

**Comment by adilno54** [comment]
It's Meta+Shift+A for me (Move window left), and it shade one window on top (only the title bar visible) and the other window full size under it.

**Comment by peterfajdiga** [comment]
Oops, yes, I meant Meta+Shift+A. It seems you're in stacking mode (named after i3's stack layout). You can toggle stacking mode with Meta+X.
