### ISSUE TITLE
Karousel not starting properly on boot.

### ISSUE THREAD

**Issue by Maxinova** [peterfajdiga/karousel#10]
When I log into my session, Karousel doesn't work initially, even though the script is activated in KDE settings (the little tick is there). To get it to function, I have to untick the script, apply the changes, then tick it again and apply once more.

As a workaround, I created a script that runs when the session connects, using the following:

```
#!/bin/zsh

kwriteconfig5 --file kwinrc --group Plugins --key karouselEnabled false
qdbus org.kde.KWin /KWin reconfigure

sleep 1

kwriteconfig5 --file kwinrc --group Plugins --key karouselEnabled true
qdbus org.kde.KWin /KWin reconfigure
```

However, this is not an ideal solution.

**Comment by Maxinova** [comment]
Hmm, I just disabled my auto-restart script, and it appears to be functioning correctly now. I'm using Arch, and there have been some system updates in the last few days, along with kde plasma updates; perhaps that fixed the issue. I'm sorry for the inconvenience. I should have retried by myself before opening an issue.

**Comment by peterfajdiga** [comment]
No problem at all, thank you for reporting! I'll close this issue for now, but please re-open it, if it happens again.
