### ISSUE TITLE
Changing Keybindings

### ISSUE THREAD

**Issue by jjvctr** [peterfajdiga/karousel#12]
It's not clear in the documentation how one could change the script's keybindings, it overlaps with some of the Plasma ones, it is not a feature yet? Should I modify the script for it? If so wich one?

**Comment by peterfajdiga** [comment]
Hi, they can be configured in KDE System Settings among KWin's own keyboard shortcuts. I've added this to the readme, thanks for the feedback!

As for overlapping with the default Plasma keyboard shortcuts, you probably mean Meta+S and Meta+D, right? Unfortunately, Meta+Down and Meta+Right are also already taken.
