### ISSUE TITLE
Bug with [Burn-My-Windows] effects.

### ISSUE THREAD

**Issue by alr86** [peterfajdiga/karousel#13]
This plugin has a problem with all [Burn-My-Windows] effects because the first-minute program starts at half height and then resizes height.

**Comment by peterfajdiga** [comment]
Hi, thanks for the report! Which effect specifically? I've tested with Hexagon and TV Effect, but I couldn't reproduce. Are you also using kwin4_effect_geometry_change or any other downloaded effects? Are you running on X11 or Wayland? Does this happen every time you open a new window or in just some specific cases?
Thanks in advance for your answers.

**Comment by alr86** [comment]
I don't know why and how, but now I tried both X11 and Wayland and had no problem! 😁
thanks anyway ❤️

**Comment by peterfajdiga** [comment]
Thanks for the update. I'm closing this now, feel free to re-open it, if the problem returns.

**Comment by alr86** [comment]
h
