### ISSUE TITLE
Karousel does not respect window rules under wayland.

### ISSUE THREAD

**Issue by baduhai** [peterfajdiga/karousel#14]
Everything is tiled under wayland, even programs you explicitly tell karousel to ignore. This is likely an upstream issue.

**Comment by peterfajdiga** [comment]
Hi, thanks for the report. One reason it would work on X11, but not on Wayland, is that some windows have a different class name on Wayland, e.g. Dolphin has "dolphin" on X11, but "org.kde.dolphin" on Wayland.

If it doesn't work on X11 either, then it's possible that you have a syntax error somewhere in the window rules JSON. At the moment it just silently fails and ignores the rules. I need to figure out a way to display an alert dialog in this case.

**Comment by peterfajdiga** [comment]
I've added a notification message that is displayed when the JSON is malformed. If you try the latest release (0.4), do you get this notification?

**Comment by baduhai** [comment]
So, I don't know what I've changed(I don't think my json was malformed), but it started working now. The only windows that don't respect the rules are windowed widgets now, like the timer. Though I have a feeling that it's because I don't have the correct class name, or because their class name is wonky under wayland.
