### ISSUE TITLE
Bug with [Burn-My-Windows] effects

### ISSUE THREAD

**Issue by alr86** [peterfajdiga/karousel#16]
## Steps:
 1. Open an app
 2. ‌‌Bring the app to the accessible mode and resize it's height
 3. Close the app and re-open it again

After running the software, it is first executed with the height we gave it last time but Stretched to the size of the screen height.
Some apps like "Plasma System Settings" run perfectly every time, some like "Nemo" run like this, and some like "xfce4-terminal" run with bugs every time;

Video: https://easyupload.io/rlxih4

## System:
 - OS: Arch Linux
 - DE: KDE Plasma 5.27.7 
 - Display server: Wayland 1.22.0-1
 - Tested effect: Hexagon
 - Tested app: Nemo file manager
 
 (I had already sent this error but did not find the Re-Open option)

**Comment by peterfajdiga** [comment]
Thanks for the detailed report and for the video! I was able to reproduce the issue on Wayland. However I don't think there's anything I can do about it.

It seems to me that this is how the effect works — it seems to base the animation on the first frame of the client and doesn't show updates until the animation is finished. In your video you can see that the Nemo window starts empty and is only updated (its contents appear) after the animation completes. Other effects (like Glide and Scale) seem to keep updating the client during the animation.
