### ISSUE TITLE
Karousel doesn't work out of the box on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by doenietzomoeilijk** [peterfajdiga/karousel#21]
Maybe this is a useful addition to the readme: when installing Karousel on Tumbleweed, it won't start. The journal will have something about `kwin_scripting: Component failed to load:  (file:///home/max/.local/share/kwin/scripts/karousel/contents/code/main.qml:3:1: module "org.kde.notification" is not installed`. The solution is to `zypper in knotifications-imports`, and restarting (logout/login) kwin.

Hope this helps anyone.

**Comment by peterfajdiga** [comment]
Thanks for letting me know that the `org.kde.notification` module is not installed by default in all KDE installations. I've added a list of QML dependencies to the readme.
