### ISSUE TITLE
Feature request - resize all columns to fit monitor

### ISSUE THREAD

**Issue by baduhai** [peterfajdiga/karousel#22]
I would personally use this mostly with 2 windows open, but it would be cool if there was a shortcut that automatically resize all columns equally to fit the display. Especially useful on ultrawide.

**Comment by peterfajdiga** [comment]
Hi, I agree, this would be useful. Currently there's two shortcuts that help you fill up your display: Meta+Ctrl++ and Meta+Ctrl+-, but they don't make the columns equally wide.
