### ISSUE TITLE
Window rules have no effect

### ISSUE THREAD

**Issue by arielchuri** [peterfajdiga/karousel#24]
Love this work. The _Window Rules_ to ignore certain windows does not work for me (endeavorOS). 
TY.

**Comment by peterfajdiga** [comment]
Hi, thanks!

Can you share your Window Rules JSON? Are you using X11 or Wayland?

**Comment by arielchuri** [comment]
I am on Wayland via endeavorOS.
I think it is just the default JSON:
[
    {
        "class": "ksmserver-logout-greeter",
        "tile": false
    },
    {
        "class": "kcalc",
        "tile": false
    },
    {
        "class": "kfind",
        "tile": true
    },
    {
        "class": "kruler",
        "tile": false
    },
    {
        "class": "yakuake",
        "tile": false
    },
    {
        "class": "yakuake",
        "tile": false
    },
    {
        "class": "krunner",
        "tile": false
    },
    {
        "class": "zoom",
        "caption": "Zoom Cloud Meetings",
        "tile": false
    },
    {
        "class": "zoom",
        "caption": "zoom",
        "tile": false
    },
    {
        "class": "jetbrains-idea",
        "caption": "splash",
        "tile": false
    },
    {
        "class": "jetbrains-studio",
        "caption": "splash",
        "tile": false
    },
    {
        "class": "jetbrains-idea",
        "caption": "Unstash Changes|Paths Affected by stash@.*",
        "tile": true
    },
    {
        "class": "jetbrains-studio",
        "caption": "Unstash Changes|Paths Affected by stash@.*",
        "tile": true
    }
]

**Comment by peterfajdiga** [comment]
Thanks for the info. I don't use Wayland, but it's possible that window class names are different there.

**Comment by peterfajdiga** [comment]
I've checked today and they are indeed different for some programs. I've updated the JSON here with the Wayland class names:
```
[
    {
        "class": "ksmserver-logout-greeter",
        "tile": false
    },
    {
        "class": "org.kde.kcalc",
        "tile": false
    },
    {
        "class": "org.kde.kfind",
        "tile": true
    },
    {
        "class": "org.kde.kruler",
        "tile": false
    },
    {
        "class": "org.kde.krunner",
        "tile": false
    },
    {
        "class": "zoom",
        "caption": "Zoom Cloud Meetings",
        "tile": false
    },
    {
        "class": "zoom",
        "caption": "zoom",
        "tile": false
    },
    {
        "class": "jetbrains-idea",
        "caption": "splash",
        "tile": false
    },
    {
        "class": "jetbrains-studio",
        "caption": "splash",
        "tile": false
    },
    {
        "class": "jetbrains-idea",
        "caption": "Unstash Changes|Paths Affected by stash@.*",
        "tile": true
    },
    {
        "class": "jetbrains-studio",
        "caption": "Unstash Changes|Paths Affected by stash@.*",
        "tile": true
    }
]
```
Can you try if it works with this JSON?

**Comment by arielchuri** [comment]
That works. I added: org.kde.yakuake. ty.

**Comment by peterfajdiga** [comment]
I've added Wayland class names to the default window rules.
