### ISSUE TITLE
A way to resize column width gradually with shortcuts rather than large steps

### ISSUE THREAD

**Issue by quissberry** [peterfajdiga/karousel#25]
Currently (based on observation), when resizing a column using shortcuts, it likes to resize to in increments to completely remove another column from field of view or completely add another column to field of view. 
I understand how this could be quicker than having it go gradually but it makes changing the exact column width impossible without using the mouse and is sometimes counterintuitive in some situations. 
Maybe making an addition gradual version (or setting) of the shortcut would be the best of both worlds?

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion. I'm not too happy with how it works currently either. I'm thinking of adding steps, as you suggested, as well as adding new shortcuts for `grow left`, `grow right`, `shrink left`, `shrink right`. But I don't yet have a full idea of how to make it all work together.
