### ISSUE TITLE
Incompatibility Issue with KDE Plasma 6

### ISSUE THREAD

**Issue by Maxinova** [peterfajdiga/karousel#29]
Hi,

Karousel appears to be incompatible with KDE Plasma 6 RC1. Are there plans for an update to ensure compatibility with the final release of Plasma 6?

**Comment by peterfajdiga** [comment]
Hi, thanks very much for the heads-up! It will be updated, but I don't know how soon. At the latest a few weeks after the stable release of KDE Plasma 6.

**Comment by peterfajdiga** [comment]
Porting is in progress, but there's a lot of fixing that needs to be done. If anyone knows of a list of breaking changes in the Kwin scripting API, please let me know.

**Comment by Maxinova** [comment]
I don't know much about it, but I could find those two links that could help :
https://develop.kde.org/docs/plasma/kwin/
https://invent.kde.org/plasma/kwin/-/wikis/Porting-your-scripts-to-KWin-6

**Comment by peterfajdiga** [comment]
Thanks. I've already found these, but they're both quite outdated/incomplete.

But regardless, I've had some time this weekend and I think I've got it working. I'll test it for about a week to see if there's still any issues. For the impatient, you can try the kwin6 branch.

**Comment by Maxinova** [comment]
Oh nice ! I think I'll try it tomorrow. Would you like to get some feedback about it if I find bugs ?

**Comment by peterfajdiga** [comment]
Yes, please :)

**Comment by peterfajdiga** [comment]
Yes, please :)

**Comment by Maxinova** [comment]
I think I installed it correctly. I can turn it on in the Kwin script menu and adjust the settings. However, it doesn't seem to change anything. Windows aren't tiled, either by default or when I use the keyboard shortcut (meta + space).

It might be because of an installation issue. To install it, I just copied everything from the package folder into ~/.local/share/kwin/scripts/karousel.

**Comment by peterfajdiga** [comment]
It needs to be built first, running `make install` will take care of it. For your convenience, here's a built package: [karousel_kwin6_wip.tar.gz](https://github.com/peterfajdiga/karousel/files/14557525/karousel_kwin6_wip.tar.gz)

**Comment by Maxinova** [comment]
Thanks ! Got it working. I'll keep you updated if I find any issue.

**Comment by baduhai** [comment]
Looking good on Plasma 6, haven't run into any issues so far.

**Comment by baduhai** [comment]
So I've run into a few issues, which I think are ultimately the same. The workspace switching popup gets tiled along with other windows. Same issue with the panel editing tools and alt-tab popup, they also get tiled when they shouldn't.

**Comment by peterfajdiga** [comment]
@baduhai I've fixed the issue with the popups getting tiled. If you notice any more windows that are tiled, but shouldn't be, please open an issue.

**Comment by peterfajdiga** [comment]
Version 0.8 supports Plasma 6 (and only Plasma 6).
