### ISSUE TITLE
Center column of focused window

### ISSUE THREAD

**Issue by matteganau** [peterfajdiga/karousel#35]
I'm not sure if this is a bug or or a feature request.

Currently it is only possible to center a window if it occupies the entire column. If a window is tiled in a column with another window the shortcut for 'Center focused window' has not effect. It would be useful to be able to center the column of a focused window.

**Comment by matteganau** [comment]
OK, I must have been trying to center a window that was in the end column and it appears that focused windows in the start or end column cannot be centered if there is more than one column.

**Comment by humanplayer2** [comment]
This confused me so, so much today. I had two windows open, jointly not filling up the width of my ultrawide monitor. I could switch between them, but I could not get the one I focused on to center.

Ficen you description, I added wide terminals on the outsides of the two windows I was actually using, and presto.

Now I'll just run two terminals on every desktop 👌😁

**Comment by peterfajdiga** [comment]
Consider using the _Center focused column_ scrolling mode, which allows scrolling past the first/last column.

Now that I think about it, maybe the default _Only scroll as necessary_ should also allow scrolling past the first/last column... :thinking:  Thanks for the valuable feedback!

**Comment by humanplayer2** [comment]
For me, centering the focused window is overkill. I often have two windows side-by-side, where I'd prefer to not center when switching focus.

I'd really appreciate that the default mode allowed scrolling past the first and last columns.

If you can point me to where to look and what to do, I'd also glad try my hand at a pull request.
