### ISSUE TITLE
Karousel: Window Movement Issue in Multi-Screen Setup on plasma 6 git version

### ISSUE THREAD

**Issue by Riebeck-one** [peterfajdiga/karousel#37]
Karousel shifts all windows to the active screen in a multi-screen setup instead of remaining on the primary screen.

Steps to replicate:

- Open windows on the primary screen.
- Click anywhere on another screen.

**Comment by peterfajdiga** [comment]
Thanks for the report! I can confirm this bug, but unfortunately in Plasma 6 there doesn't seem to be any way to find out which screen is the primary one.

I'm trying to decide what's the best way to work around this limitation.

**Comment by Maxinova** [comment]
I just found out about this script for plasma 6 :
https://github.com/wd5gnr/moveallwindowstoscreen6/tree/main
It let's the user send all windows to a selected screen via a keyboard shortcut. Maybe it could help ?
The relevant code seems to be this :
```
function isRelevant(client) {
    return !client.specialWindow;
}

function moveAllWindowsToScreen(screen) {
    var allClients = workspace.windowList();   // was clientList in v5
    var relevantClients = allClients.filter(function(client) {
        return isRelevant(client);
    });

    for (var i = 0; i < relevantClients.length; ++i) {
        var client = relevantClients[i];
        workspace.sendClientToScreen(client, workspace.screens[screen]);   // was just screen number in v5
    }
}

function moveAllTo0() {moveAllWindowsToScreen(0)}
function moveAllTo1() {moveAllWindowsToScreen(1)}
function moveAllTo2() {moveAllWindowsToScreen(2)}
function moveAllTo3() {moveAllWindowsToScreen(3)}
registerShortcut("Move All Windows To Screen 0", "Move All Windows To Screen 0", "", moveAllTo0);
registerShortcut("Move All Windows To Screen 1", "Move All Windows To Screen 1", "", moveAllTo1);
registerShortcut("Move All Windows To Screen 2", "Move All Windows To Screen 2", "", moveAllTo2);
registerShortcut("Move All Windows To Screen 3", "Move All Windows To Screen 3", "", moveAllTo3);
```

Maybe` workspace.screens[0] `points out to the primary screen ?

**Comment by JulioJair** [comment]
@peterfajdiga Thanks for your awesome work btw. I've been using Karousel for months. I recently updated to Plasma 6 and found myself in the same exact situation.

If the script that @Maxinova founds out works as expected, it would be nice if the Karousel windows to be fixed to the primary screen

**Comment by peterfajdiga** [comment]
Unfortunately `workspace.screens[0]` doesn't necessarily point to the primary screen.

**Comment by Riebeck-one** [comment]
A possible temporary solution might be to force Karousel to stay on a single screen, regardless of whether it's the primary one. Users could then utilize keyboard shortcuts to switch between different screens.

**Comment by peterfajdiga** [comment]
@Riebeck-one Yes, that would work. But it would be a bit annoying having to switch to your preferred screen after every startup.

Another possible solution/workaround I'm thinking of would be to implement per-screen tiling with a keyboard shortcut to disable tiling on the current screen. This has the same problem of having to do this after every startup, though.

**Comment by peterfajdiga** [comment]
@Riebeck-one I've implemented the solution you've described, with the keyboard shortcut Meta+Ctrl+Return by default (picked arbitrarily, alternative suggestions welcome).

**Comment by Riebeck-one** [comment]
Oh, nice! Can't wait to try this out.

**Comment by Riebeck-one** [comment]
@peterfajdiga  Just did the update, it's much more comfortable to use now. Thanks!
