### ISSUE TITLE
Panel Editing Mode and Plasmoid Popup Display Tiling Issue

### ISSUE THREAD

**Issue by Maxinova** [peterfajdiga/karousel#38]
The panel editing mode, along with the right-click-like popup that appears when you hover over a plasmoid, is tiled when it shouldn't be.

Steps to replicate:

- Enter panel editing mode (e.g., by right-clicking an existing panel and selecting "Enter Edit Mode").
- Hover over a plasmoid with the cursor.

![image](https://github.com/peterfajdiga/karousel/assets/721025/01a9b19c-5e8b-4ff7-acae-ea58fb2513b7)

**Comment by peterfajdiga** [comment]
Thanks for the report.
These windows are marked as normal windows, so the only way I see to solve this is to add these entries to the window rules:
```
    {
        "class": "plasmashell",
        "tile": false
    },
    {
        "class": "org.kde.plasmashell",
        "tile": false
    },
```

Unfortunately this also removes tiling from some other windows, for example the wallpaper selection dialog.

Regardless, I'll add this to the default window rules.
