### ISSUE TITLE
Feature Request - Window border highlight

### ISSUE THREAD

**Issue by baduhai** [peterfajdiga/karousel#4]
I'm absolutely loving karousel, I've finally found a tiling mode that work for me. It would be really nice if karousel had a window border highlight the way traditional tiling WMs do. I don't know if this would be something that would be built as a kwin script or a desktop effect, but I find myself getting lost when it comes to which window is currently focused. I use the "Dim Inactive" desktop effect to darken inactive windows, but it's suboptimal.

**Comment by baduhai** [comment]
By a window border highlight, I mean this: 
![image](https://github.com/peterfajdiga/karousel/assets/31864305/408f0b1e-e930-45ab-8db4-2a514523d1fe)

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion, but I'm not sure this is doable with the Kwin Scripting API. Even if it is, this should be a separate script and not part of Karousel, so it could be used even without Karousel.

In any case, a different window decoration may solve your issue. Here's one option: https://store.kde.org/p/1217715/ . Another option would be the Bismuth window decoration from here: https://github.com/Bismuth-Forge/bismuth/tree/master/src/kdecoration (I'm assuming it can be used independently from the [Bismuth](https://github.com/Bismuth-Forge/bismuth) script).
