### ISSUE TITLE
Feature Request: Windows without borders

### ISSUE THREAD

**Issue by Graninius** [peterfajdiga/karousel#40]
Please, add "Windows without borders" option.
Thank you )

**Comment by peterfajdiga** [comment]
Changing the appearance of windows is not a job of Karousel. I'm not even sure this is doable with the Kwin scripting API.

Kwin has a separate system for this. Try to find or create a borderless window decoration. Or you can try following [this Reddit comment](https://www.reddit.com/r/kde/comments/qtmxal/comment/hkkmwqw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

**Comment by Graninius** [comment]
> Changing the appearance of windows is not a job of Karousel. I'm not even sure this is doable with the Kwin scripting API.
> 
> Kwin has a separate system for this. Try to find or create a borderless window decoration. Or you can try following [this Reddit comment](https://www.reddit.com/r/kde/comments/qtmxal/comment/hkkmwqw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
**Polonium** [https://github.com/zeroxoneafour/polonium](url) works with this feature perfectly.
