### ISSUE TITLE
Use whitelist for selecting which windows to tile

### ISSUE THREAD

**Issue by mphe** [peterfajdiga/karousel#41]
I don't want to tile anything by default except certain windows, like terminals.

I have tried the following rule and reloaded the plugin, but it had no effect. All windows were still tiled automatically.

```json
[
    {
        "class": ".*",
        "tile": false
    },
    {
        "class": "Alacritty",
        "tile": true
    }
]
```

Is it possible to achieve this behavior somehow?

**Comment by peterfajdiga** [comment]
Unfortunately, the class selector doesn't support regex, only the caption selector does. I admit this is confusing, but I didn't think it was needed for class, because it's not as varying as the caption.

There is no other way to achieve a whitelist behavior.

I can add regex support for the class selector, but it will make window rules config uglier, because dots will need to be escaped, turning classes like `org.kde.plasmashell` into `org\\.kde\\.plasmashell`.

I'm experimenting with this in the window_rules_class_regex branch.

**Comment by mphe** [comment]
Nice, I will check it out later!
One way to keep backwards compatibility could be to introduce another field "class_regex" which is mutually exclusive with "class" and will be interpreted as regex, while the other doesn't.

**Comment by mphe** [comment]
I've just tested the feature and it works fine as such. However, due to tiled windows always being kept below floating windows (or floating windows above tiled windows), it is now pretty much unusable. E.g. with a maximized non-tiled window open, I will never see my terminals.
Is there a reason tiled windows are kept below? Or could there also be a third layout option that does not modify window z-order in any means?

**Comment by peterfajdiga** [comment]
All tiling window managers I've tried keep floating windows above tiled
ones. Karousel didn't initially, but that made for a frustrating
experience. Obscured floating windows are harder to locate and switch to
without using another tool (e.g. a taskbar).

That said, I can add an option to disable it for your use case.

**Comment by mphe** [comment]
I'm coming from Awesome and try to replicate my setup in KDE. Awesome does not come with any forced z-ordering by default and I also never used any. 
My setup made every window floating by default and only a selection of windows non-floating (as mentioned in top post). Whatever received explicit focus (mouse click or shortcut-based focus shifting) gets raised. Never had a problem with this workflow. But I also use the taskbar, so maybe that is not such a common thing for hardcore tiling users to do.

Anyway, having a dedicated option to toggle the behavior would be much appreciated!

**Comment by mphe** [comment]
Thank you!
