### ISSUE TITLE
No effect, no shortcuts after installation

### ISSUE THREAD

**Issue by gterras** [peterfajdiga/karousel#42]
Hi, 

On Debian sid / Plasma 5.27 / X11, tiling activated in desktop effects, fresh user :  

Installing and activating any 5.27 compatible version (so until 0.7.1) through KDE scripts screen have no effect, windows behave as normal and I can't see any "Karousel" shortcuts (I can't see any of the shortcuts displayed in the README in my settings). 

I'm sorry as this is most probably my setup at fault, I see no error in `~/.xsession-errors`, tried reinstalling kwin, tried to run the script with `plasma-interactiveconsole --kwin` with apparently no error, do you see a way to debug this? 

Thanks

**Comment by peterfajdiga** [comment]
Do you see Karousel in the list of installed Kwin scripts? Is it activated there?
Do you see any relevant errors using `journalctl -t kwin_x11 -g '^qml:|karousel' -n 20`?

**Comment by gterras** [comment]
Thanks a lot for this debug command, it told me that `org.kde.notification` wasn't installed, which I thought I did installing `libkf5notifications5` but it turns out the right package is named `qml-module-org-kde-notifications` on Debian. 

This looks wonderful, way above Bismuth that I have been using until now, can't wait to dig into all the possibilities. 

Thanks
