### ISSUE TITLE
Activate recent windows (previous/next)

### ISSUE THREAD

**Issue by xalt7x** [peterfajdiga/karousel#44]
Sometimes user needs to switch between recent windows. Such windows may not be adjacent (left/right) and they may not be at the edge (start/end).
I'd like to have keybindings for actions similar to [kwin-window-switch](https://github.com/insidewhy/kwin-window-switch) (doesn't work with Plasma 6 yet) or native window switcher (doesn't work with Karousel).

**Comment by peterfajdiga** [comment]
The native Plasma Task Switcher should work with Karousel as long as you don't set "Tiled windows skip switcher" in the Karousel settings.

Can you describe how it doesn't work? Does anything happen at all when you press the keyboard shortcut?

**Comment by xalt7x** [comment]
> The native Plasma Task Switcher should work with Karousel as long as you don't set "Tiled windows skip switcher" in the Karousel settings.

Thanks, that was it. Alt+Tab works now and to avoid popup I can just increase [KWin's DelayTime](https://userbase.kde.org/Plasma/Tips#show-alt-tab-popup-as-fast-as-possible) to some higher value (e.g., 150)

As for this issue, I'm not sure if I should close it. Additional shortcut for Task Switcher (e.g. Meta+z) works but it might break an original Alt+Tab shortcut so user may have better experience with setting it for Alternative Task Switcher.

**Comment by peterfajdiga** [comment]
Glad to hear that fixed it! As for the issue itself, I'm not sure I understand. What would such a shortcut in Karousel achieve that the native Task Switcher doesn't?

**Comment by xalt7x** [comment]
> Glad to hear that fixed it! As for the issue itself, I'm not sure I understand. What would such a shortcut in Karousel achieve that the native Task Switcher doesn't?

After some testing I've found that the native Task Switcher is fine for this.   
Thanks for your help and feedback!
