### ISSUE TITLE
Let the floating panel float

### ISSUE THREAD

**Issue by Coruscant11** [peterfajdiga/karousel#45]
Hi,

I wanted to know if it would be possible to not trigger the floating panel unfloat process ?

Without karousel:
![image](https://github.com/peterfajdiga/karousel/assets/1645347/2ad55b3e-0957-4950-a505-25f925dddb3f)

With karousel:
![image](https://github.com/peterfajdiga/karousel/assets/1645347/093f6cb3-a4b5-4af7-af81-71cefc72baf7)

You can see that the floating panel is not floating anymore.

Thanks :smile:

**Comment by peterfajdiga** [comment]
You can increase the bottom gap/margin in Karousel settings. I don't know
of another way to prevent this.

**Comment by Coruscant11** [comment]
Indeed, with a bottom margin of 28px instead of 18px.
Thank you very much!
