### ISSUE TITLE
Kwin freeze when detaching a tab in Chromium

### ISSUE THREAD

**Issue by kuroko143** [peterfajdiga/karousel#49]
Steps to reproduce:
1) Have Chromium open with several tabs open.
2) Pull one of the tabs so that it detaches and spawns a new window.
3) Kwin completely freezes and only way to get out of it is to force power off the computer.

If I disable Karousel and goes through those steps, it is fine.

**Comment by peterfajdiga** [comment]
Hi, thanks for the report! Are you using Plasma 5 or 6? X11 or Wayland?

**Comment by kuroko143** [comment]
Plasma 6.0.5, Wayland, AMDGPU

**Comment by peterfajdiga** [comment]
Thank you. Please share if you see any relevant logs after the crash. You can find them by running:
```
journalctl -t kwin_wayland -n 50
```
(you can increase the "50" to see more logs)

**Comment by kuroko143** [comment]
Jun 02 12:48:26 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:48:40 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:49:08 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:49:33 nixos kwin_wayland[1455]: kf.kio.core: "" contains supported protocols but doesn't use %u or %U in its Exec line! This is inconsistent.
Jun 02 12:49:35 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:49:51 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:50:02 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:50:11 nixos kwin_wayland[1455]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Jun 02 12:50:16 nixos kwin_wayland[1455]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
-- Boot 1de139647c254ec8953d2c81396d35ba --


I am guessing it's the Pageflip line. Might not be something you can fix.

**Comment by peterfajdiga** [comment]
Thank you. Yes, this doesn't seem like something in Karousel.
