### ISSUE TITLE
Position of icons in Taskmanager is not synchronized with window position

### ISSUE THREAD

**Issue by rkunschke** [peterfajdiga/karousel#50]
I've seen the video in the github readme. The position of the icons in the task bars task manager is changing with the windows position.
How did you do that?
Is this something which only works on x11? (I'm on wayland)

**Comment by peterfajdiga** [comment]
The video shows a custom task manager, which I've not released yet, because it's very hacky and buggy.

**Comment by Riebeck-one** [comment]
Waou I didn't even notice it when watching the video the first time, it looks really nice !

**Comment by AndydeCleyre** [comment]
I don't know if you're still working on that custom task manager, but I've opened [a merge request for this feature](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/5134) in the official task manager.

**Comment by AndydeCleyre** [comment]
I think this can be considered solved now, as of Plasma 6.4. In the task manager settings, under Behavior>Sort:, choose "By horizontal window position"

**Comment by gleyconJ** [comment]
> Acho que isso pode ser considerado resolvido agora, a partir do Plasma 6.4. Nas configurações do gerenciador de tarefas, em Comportamento>Classificar:, escolha "Por posição horizontal da janela"
> 
> EDITAR:
> 
> Embora agora que EU olho para o vídeo de demonstração, EU vejo o seu gerenciador de tarefas personalizado reflete até mesmo as colunas de várias janelas, o que é super legal, e definitivamente não nos gerenciadores de tarefas oficiais do Plasma.

"Thank you very much for posting this information, I was about to miss it, as nowhere I read about version 6.4 mentioned this. And it's already better than nothing. Now all that's missing is a way to stack icons just like we stack windows."
