### ISSUE TITLE
Conflicts with Window Rule (Decreasing Opacity)

### ISSUE THREAD

**Issue by rahim-gh** [peterfajdiga/karousel#54]
As I'm using this script I notice a big white rectangle on the left of my screen, it only appear if enable both: karousel, and windows rule (decrease the opacity). so is there a workaround to fix this or just wait until next push?

![Screenshot_20240629_090533](https://github.com/peterfajdiga/karousel/assets/77893770/d2469fb3-0d9f-4a55-955d-c822148e5bcc)

using latest version of Fedora 40, kde 6.1.1

**Comment by peterfajdiga** [comment]
Hi, thanks for the report. Can you share the window rule you're using? Is it for a specific application? If so, does that application need to have a window open for this to happen?

Also are you using Plasma 5 or 6? And X11 or Wayland?

**Comment by rahim-gh** [comment]
In kde plasma 6.1 wayland

it apears even after login imediatly in the middle, moves to left if opens a window. stay there if close all.

about window rule set globaly to decrease the opacity of active and inctive windows to 95%. set the target to unimportant

**Comment by peterfajdiga** [comment]
Thanks for the info. I've managed to reproduce the problem. The thin white window that appears on the left is xwaylandvideobridge. This window presents itself as a normal window, so it gets tiled by Karousel. I'm adding an exception to the default Karousel window rules.
