### ISSUE TITLE
Borderless Fullscreen apps sometimes get tiled

### ISSUE THREAD

**Issue by Alprolol** [peterfajdiga/karousel#55]
I realised this happened first in rocket league since it forced rocket league into about 1000 pixels tall and 600 pixels wide when I tried to alt-tab. I'm not sure exactly how to recreate it as I just moved back to openbox after having multiple problems in kde but just putting rocket league on borderless and alt-tabbing should work.

**Comment by peterfajdiga** [comment]
Hi, thanks for the report! Was this on X11 or Wayland? And which version of Plasma?

**Comment by Alprolol** [comment]
X11

**Comment by kolemcrae** [comment]
Just a vote that this happens for me with multiple games but using wayland.

**Comment by peterfajdiga** [comment]
I can't reproduce it with Rocket League. Rocket League window is not resizeable, which means Karousel will never try to tile it.

@kolemcrae Which games? Fullscreen or borderless?

**Comment by baduhai** [comment]
This happens to me too, though seldom. The most easily reproducible program it happens with is steam big picture mode. On Wayland btw.

**Comment by kelvie** [comment]
This also happens occasionally for me (on NVIDIA, never with AMD) on wayland. Is there debugging info that can help when this happens?

**Comment by Alprolol** [comment]
People are saying this happened to them on Wayland, it was X11 for me and someone also said it happens on Nvidia so I don't think it's a compilation or graphics error I think it's an error with the base code itself.

**Comment by Alprolol** [comment]
One solution I would assume to work is if an app is perfectly in line with a "fullscreen" setup (equal size to monitor and at (0.0) without decoration) it should be treated as a fullscreen app. I'm not sure how this would work in general though as an app/game could be switched after launch into borderless from fullscreen as well.

**Comment by baduhai** [comment]
Why was this closed?

**Comment by peterfajdiga** [comment]
@baduhai Thanks for the suggestion to test with Steam Big Picture Mode. For me SBPM starts in full-screen mode and if I switch to another window, it goes to tiled (windowed) mode. If I switch it back to full-screen (with Kwin's Make Window Fullscreen shortcut), it works normally without a problem.

Also, when SBPM starts, it has a transparent background, which it shouldn't have.

Does this match your experience?

**Comment by baduhai** [comment]
> @baduhai Thanks for the suggestion to test with Steam Big Picture Mode. For me SBPM starts in full-screen mode and if I switch to another window, it goes to tiled (windowed) mode. If I switch it back to full-screen (with Kwin's Make Window Fullscreen shortcut), it works normally without a problem.
> 
> Does this match your experience?

That is exactly what happens.

**Comment by peterfajdiga** [comment]
I tried to make Karousel not tile windows that start with a full-screen size, but it seems that SBPM actually starts with a smaller window before immediately resizing to full-screen. I don't see a way to discern such windows automatically, so it's probably best to make exceptions for them in Karousel's window rules.

**Comment by baduhai** [comment]
> I tried to make Karousel not tile windows that start with a full-screen size, but it seems that SBPM actually starts with a smaller window before immediately resizing to full-screen. I don't see a way to discern such windows automatically, so it's probably best to just make exceptions for them in Karousel's window rules.

For the case of SBPM, that makes sense, but the problem is when it comes to games. Most games I play default to borderless fullscreen, and are therefore susceptible to this bug.

**Comment by nerdictranslator** [comment]
Okay, dumb question perhaps, but if someone _did_ want to tile windowed-fullscreen games, on purpose, how might they go about doing that?

Not full tiling support, just easy switching from the game to other windows via the usual Karousel shortcuts? Because that's one of the "features" I liked before.

**Comment by peterfajdiga** [comment]
@nerdictranslator Alt+tab should still work. If you still want to tile them anyway, you could try using the _Toggle floating_ keyboard shortcut (Meta+Space by default).
