### ISSUE TITLE
Feature Request: Navigate windows by next/previous instead of by direction

### ISSUE THREAD

**Issue by ajgrf** [peterfajdiga/karousel#58]
I would like to navigate windows by next/previous instead of by direction. It's what I'm used to from dwm, xmonad, paperwm, etc. It will also free up some bindings to use for something else. I think there are only 4 new actions that I need:

-  Move focus to next/previous

   Focusing the next window would first look for a window below the currently focused window. If there isn't one, it would focus the top window in the next column.
- Move window to next/previous

   Moving a window to next would swap places with any window below it. If there are no windows below it but there are other windows in the column, it moves right to make a new column. If it's the only window in its column, it becomes the *top* window in the next column. (Moving a window to previous would still join columns as the bottom window.)

I also think it would be more consistent to have actions available for moving columns to the next/previous desktop, or to the desktop to the left/right/up/down, but to be honest I wouldn't use them so you may as well wait for someone to ask for them.

Thanks for all your hard work implementing Karousel, I've been using it all week and really enjoying it!

**Comment by peterfajdiga** [comment]
Thanks for the suggestion! I can see the value of freeing up a few keys,
even if it's not something I'd use myself. On the other hand, I don't want
to add too many ways to do the same thing. Let me think about it.

**Comment by ajgrf** [comment]
Thanks for implementing this! I just updated to the latest commit and it behaves exactly like I want now.
