### ISSUE TITLE
[Bug] White 'window' appears on the left side when booting into the system

### ISSUE THREAD

**Issue by ZenurikSD** [peterfajdiga/karousel#61]
Karousel version: 0.9.4
Plasma version: 6.1.4
X11 / Wayland: Wayland 

**Description:** 
When doing a system restart or booting up for the first time, a white, full-height column appears on the left side of the screen. It behaves like a window when other columns are used, but is not targetable and does not appear anywhere as a "window entity" that can be switched to.

Running `kwin_wayland --replace` fixes the issue.

https://github.com/user-attachments/assets/bb3b7ad0-c8d3-422e-820c-8fea4be31aca

**Karousel settings:**
![image](https://github.com/user-attachments/assets/8f1f74d3-3fb5-4992-9ae0-9c8bcfbdc1fc)
![image](https://github.com/user-attachments/assets/40c17295-5416-4e4e-8dc3-7ae12cdd0b08)
![image](https://github.com/user-attachments/assets/2a144df1-4067-486f-811e-585f5228b35b)

**Comment by peterfajdiga** [comment]
Thanks for the report! Can you give me the white window's class, caption (title), and type? I've just written the steps to get this info here: https://github.com/peterfajdiga/karousel/wiki/Getting-window-info

**Comment by ZenurikSD** [comment]
I don't know how to open Kwin's debug console and I can't do it by detecting the window properties since the window is not targetable, I just end up selecting the desktop behind it.

**Comment by peterfajdiga** [comment]
@ZenurikSD You can open Kwin's debug console with KRunner (Press alt+space and type "kwin debug console").

**Comment by ZenurikSD** [comment]
Here are the window's properties:
- resourceClass: xwaylandvideobridge
- caption: (it's in Portuguese but it is the same as the resourceClass essentially)
- windowType: NET::Normal

**Comment by peterfajdiga** [comment]
Do your window rules contain this entry?
```
    {
        "class": "xwaylandvideobridge",
        "tile": false
    },
```

This was added to the default window rules in 0.9.3, but it's possible it's missing if you already had customized window rules when you updated to 0.9.3. I should probably hard-code this rule, instead of leaving it configurable.

**Comment by ZenurikSD** [comment]
Yeah, I had customized it and this entry wasn't there. I added it and after another reboot, the window is gone! Thank you.

**Comment by peterfajdiga** [comment]
Great! Thanks again for the report and all the info.
