### ISSUE TITLE
REQUEST FOR FEATURES: reuse concepts from desktopneo.com

### ISSUE THREAD

**Issue by gleyconJ** [peterfajdiga/karousel#69]
Thank you again for your FANTASTIC Karousel, I'm coming back to ask to make it even more powerful!

Check out the site:

[https://desktopneo.com/](https://desktopneo.com/)

Their features:

### PANELS
ADJUST = Karousel 🤙🏻
PIN = Karousel + KwinTiles 🤙🏻
MINIMIZE = Karousel ❌

### APP CONTROL
STATUS BAR = Plasma does 🤙🏻
APP LAUNCHER = Plasma does 🤙🏻
PANEL MANAGEMENT = Karousel ❌

### APP MENU
Not interested

### FINDER
Not interested

### GESTURE OVERVIEW
Not interested (FOR NOW)

### TAGS
Not interested

### SEARCH & FILTERS
Not interested

### GAZE
SELECT = Karousel ❌
The rest is not interesting

### TOUCH
Not interested

### VOICE
Not interested

§§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§ §§§

### WELL, IN SUMMARY:

**I think the most important item that could be implemented right away is the minimize feature.**

[https://desktopneo.com/assets/images/feature-minimize.gif](https://desktopneo.com/assets/images/feature-minimize.gif
)
§§§

**An additional plugin to simulate alt+tab in the same style:**

[https://desktopneo.com/assets/images/appcontrol-full.jpg](https://desktopneo.com/assets/images/appcontrol-full.jpg
)
§§§

**And a plasmoid to be placed on the panel or desktop, similar to the drawings (1, 2, 3) in the GAZE subtopic:**

[https://desktopneo.com/#input](https://desktopneo.com/#input)

**Comment by peterfajdiga** [comment]
Hi, thanks for taking the time to type this. However, this is out of scope for this project (some of it may not even be doable).
For future issues, please pick a specific (sing) topic and use one of the issue templates (I've just added one for feature requests).

**Comment by gleyconJ** [comment]
Hello, I know it is boring to have to deal with requests for things that are not in your plans and that can even distort your thoughts about what you planned yourself. But do you think these features make no sense to Karousel?

 §§ §§§§§§

 Minimize:
 https://desktopneo.com/assets/images/feature-minimize.gif

 §§

 Alt Tab for Karousel
 https://desktopneo.com/assets/images/appcontrol-full.jpg

 §§

 Plasmoid in Workspace Style and Activities (but for Karousel)
 https://desktopneo.com/#input

 §§ §§§§§§

 I believe that minimize is implemented within Kwin's own script. Since this already happens horizontally when we group columns of programs (in X11).

 And that Alt Tab and Plasmoide are two new programs but with Karousel titles. Example:
 * Karousel PAGE
 * Karousel Task Switcher

 Totaling a Karousel trilogy.

 Do you think this runs away from your goals? And if so, could you tell me why would you disapprove of these features I mentioned here?

 I'm not a programmer, just a fan of your work. I don't know about the implementation difficulties, but I see these 3 organically perfect items for Karousel.

 Yours sincerely.,

**Comment by gleyconJ** [comment]
### Why do I consider these important requests!

 **MINIMIZE**

 Why do I consider it minimar the suggested form ([https://desktopneo.com/assets/images/feature-minimize.gif](https://desktopneo.com/assets/images/feature-minimize.gif)), important? When we minimize applications in the normal shape of plasma, to the restaurants, it comes back in another position different from what it was. But if she just shrinks, when she stretches, she will have no reason to go to the end, right, left, or anywhere other than exactly where she is.

In this case, this would be a way to solve this problem of reappearance disorder of minimized windows.

**Alt Tab for Karousel**
[https://desktopneo.com/assets/images/appcontrol-full.jpg](https://desktopneo.com/assets/images/appcontrol-full.jpg)

 Here the idea is the same as the previous one. Overcome some discomfort of native or low -dotted functions from stores. None of them simulates the carousel mounted by the same. You have a Montod carousel, entering, the alternation is not intuitive with the ones we currently have (natively and the store downloads). If there was an Alt Tab that simulated the same as the desktopnele would be perfect.

 The part where the application icons could be only the same as we put in our launcher favorites the most recently used (plasma native functions). The search bar at the top would be Krunner (also native).

 When this window was summoned with Alt Tab you simply alternate the windows. But if you hold Meta + K (same is Meta + G 'grid' and Meta + W 'overview'), this function would remain fixed on the screen so that you rearrange the windows (lower) or click on the programs set on the (top) waiting for them to open and you still continue to organize their positions.

**Plasmoide Karousel**
[https://desktopneo.com/#input](https://desktopneo.com/#input)

 This one I consider a luxury! For it would have the same functions as the previous item, but at the level of panel (miniaturized). But would make the resource round.

§§§

I believe I am not corrupting your work suggesting such resources. But if it were like this now, I believe many eleogy would be fabrics about this work that is already fantastic and highly praised by those who use real computer.

 In addition, thank you very much. Yours sincerely.

**Comment by gleyconJ** [comment]
One more consideration

 ALT TAB FOR KAROUSEL

 If Meta + W serves to drag area 1 windows to area 3, for example. And also create or delete areas. And also use Krunner.
 If Meta + G serves to go from area 1 to program X, area 3, for example. And also to see all the programs open in a single view.
 Then Meta + K would serve from column A to column H (off -screen - normal; inside the screen - with this feature). And also order the Karoussel windows in a single view. Plus the Krunner, favorites (and/or recent).

 Well that's it.

 PS: I write with good intentions.

**Comment by peterfajdiga** [comment]
Thanks again for your input! These features do make sense and would be really nice to have, especially the minimize and the overview features, which I've actually considered before (or at least something similar to them), but I simply don't have the time to implement them.

The minimize feature would be a lot more work than it seems (or it might not even be possible), because it needs to render a placeholder in place of a minimized column.

As for the overview (_panel management_) feature, this is something that I've been considering for a while, and still am, but again, I don't have the time.

**Comment by gleyconJ** [comment]
Oh yes, thank you very much for your feedback!
 I just needed to hear something that comforted my heart.
 And that really comforts me! Because it is a problem that cannot be solved (lack of time).

 Have you considered leaving a reserved space on the Karousel's main page with a request for recruitment of programmers who are willing to help you implement these recovers you have desire, but have no logistics (time) to solve them?

 Detail: I don't know how it works, but I've seen this type of statement on some pages, where the original author asks to join force with other developers.

 Well if it makes it clear that you want only for such item (item x, or y…).

 But it's just another input of mine. 😅😅😅
