### ISSUE TITLE
[Feature request] Remove window borders on tiled windows, but keep them on floating ones.

### ISSUE THREAD

**Issue by arklese1zure** [peterfajdiga/karousel#73]
Pretty much what the title describes. In my use case, I have a small screen and would appreciate the extra pixels. The Krohnkite script has this feature.

**Comment by arklese1zure** [comment]
I was planning on using LightlyShaders in order to make the windows look nice, but I'm aware it's a niche use case. In fact I pretty much did what you suggested and made my plasma panels auto-hide, and I think I can build a nice-looking desktop around that.
Thanks for the input!

**Comment by gleyconJ** [comment]
Hey there! You're welcome. 🙂
