### ISSUE TITLE
Feature Request - Pin Window

### ISSUE THREAD

**Issue by wesbluemarine** [peterfajdiga/karousel#8]
Would be possibile to add a shortcut and/or a kwin button for pinning one window?
The pinned window would act similar to pinned tabs on web browsers, it would be fixed as the first window on the left and the scolling would start with following windows, leaving the pinned one always visible.

**Comment by peterfajdiga** [comment]
This is actually already planned, but I haven't gotten around to implementing it. Thanks for opening the issue for it!

**Comment by peterfajdiga** [comment]
Karousel now reacts to Kwin-tiled windows. When, for example, quick tiling a window to the left, Karousel grid is moved to the right of it.
